name: Deploy Lambda Code to S3

on:
  push:
    branches:
      - main  # Execute a pipeline ao fazer push na branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout o c칩digo do reposit칩rio
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar ferramentas necess치rias
      - name: Install zip
        run: sudo apt-get install -y zip

      # Configurar AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      # Enviar o arquivo zip para o bucket S3
      - name: Zip and Upload Lambda Functions Dynamically
        run: |
          BUCKET_NAME="lambda-upfunnels-code"
          cd code;
          for dir in */; do
            if [ -d "$dir" ]; then
              lambda_name=$(basename "$dir")
              zip -r "${lambda_name}.zip" "$dir" -x "*.git*"  # Exclui arquivos e diret칩rios Git
              aws s3 cp "${lambda_name}.zip" s3://${BUCKET_NAME}/${lambda_name}.zip
            fi
          done

      # Configure o Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5 

      # Configurar as credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
          terraform_wrapper: false
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: | 
          cd infra; WORKSPACE=production make init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd infra; WORKSPACE=production make plan

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: | 
          cd infra; WORKSPACE=production make apply

